version: '3.8'

services:

  # Base de données PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application Spring Boot
  app:
    build: .
    container_name: taskmanager-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskmanager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      JWT_SECRET: MonSuperSecretTresLongPourJWTTaskManager2024
      JWT_EXPIRATION: 86400000
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: