# ========================
# Serveur
# ========================
server.port=8080

# ========================
# Base de données PostgreSQL
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / Hibernate
# ========================
# create-drop = recrée les tables à chaque démarrage 
# update      = met à jour sans effacer les données
# validate    = vérifie sans toucher (prod)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ========================
# Nom de l'app
# ========================
spring.application.name=task-manager